image: maven:3.9.9-eclipse-temurin-21

stages:
  - compile
  - test
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  key: "$CI_PROJECT_ID-maven"
  paths:
    - .m2/repository

compile:
  stage: compile
  script:
    - mvn $MAVEN_CLI_OPTS -q clean compile

unit_test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -q test
  needs:
    - compile

package_jar:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS -q clean package -DskipTests
  needs:
    - unit_test
  artifacts:
    name: "ilicense-jars-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    paths:
      - ilicense-client/target/*.jar
      - ilicense-spring-boot/ilicense-spring-boot-autoconfigure/target/*.jar
      - ilicense-spring-boot/ilicense-spring-boot-starter/target/*.jar
