image: maven:3.9.9-eclipse-temurin-21

stages:
  - compile
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  key: "$CI_PROJECT_ID-maven"
  paths:
    - .m2/repository

compile:
  stage: compile
  script:
    - mvn $MAVEN_CLI_OPTS -q clean compile

unit_test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -q test
  needs:
    - compile
